name: UFEMISM Test Suite - install Python
run-name: ${{ github.actor }} - UFEMISM Test Suite - install Python
on:
  workflow_call:

jobs:
  install_python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'

      - run: pip install -r tools/python/requirements.txt

