name: UFEMISM Test Suite - run and analyse integrated tests
run-name: ${{ github.actor }} - UFEMISM Test Suite - run and analyse integrated tests
on:
  workflow_call:

jobs:

  idealised_Halfar_dome_Halfar_40km:
    uses: ./.github/workflows/zz_integrated_test_idealised_Halfar_dome_Halfar_40km.yml
