# The full UFEMISM Test Suite

name: UFEMISM Test Suite (full)
run-name: ${{ github.actor }} - UFEMISM Test Suite (full)
on: workflow_dispatch

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:

      - name: Install nix
        uses: cachix/install-nix-action@v22

      - name: Get nix version
        run: |
          nix --version

      - name: Build UFEMISM with nix
        run: |
          nix build github:IMAU-paleo/UFEMISM2.0/${{github.sha}}?dir=tools/flake

      - name: Save UFEMISM build to cache
        uses: actions/cache/save@v3
        with:
          path: result
          key: UFEMISM_build

  run-unit-tests:
    needs: setup
    runs-on: ubuntu-latest
    steps:

      - name: Restore UFEMISM build from cache
        uses: actions/cache/restore@v3
        with:
          path: result
          key: UFEMISM_build

      - name: Check if we have it
        run: |
          ls -a
          ls result
          ls result/bin

    #  - name: Checkout UFEMISM repository
    #    uses: actions/checkout@v4

    #  - name: Install MATLAB
    #    uses: matlab-actions/setup-matlab@v2.2.0

    #  - name: Another MATLAB test
    #    uses: matlab-actions/run-command@v2
    #    with:
    #      command: disp('Hello world!')
