name: UFEMISM Test Suite - analyse integrated tests
run-name: ${{ github.actor }} - UFEMISM Test Suite - analyse integrated tests
on:
  workflow_call:

jobs:
  analyse_integrated_tests:
    runs-on: macos-latest
    steps:

      - name: Checkout UFEMISM repository (from pull request)
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/checkout@v4
        with:
         repository: ${{ github.event.pull_request.head.repo.full_name }}
         ref: ${{ github.event.pull_request.head.ref }}

      - name: Checkout UFEMISM repository (from manual run)
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/checkout@v4

      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v2.2.0
        with:
          cache: true

# integrated_tests/idealised/Halfar_dome/Halfar_10km

      - name: Download temporary scoreboard file for integrated_tests/idealised/Halfar_dome/Halfar_10km
        uses: actions/download-artifact@v4
        with:
          name: temporary_scoreboard_integrated_tests_idealised_Halfar_dome_Halfar_10km
          path: automated_testing/integrated_tests/idealised/Halfar_dome/Halfar_10km

# integrated_tests/idealised/Halfar_dome/Halfar_20km

      - name: Download temporary scoreboard file for integrated_tests/idealised/Halfar_dome/Halfar_20km
        uses: actions/download-artifact@v4
        with:
          name: temporary_scoreboard_integrated_tests_idealised_Halfar_dome_Halfar_20km
          path: automated_testing/integrated_tests/idealised/Halfar_dome/Halfar_20km

# integrated_tests/idealised/Halfar_dome/Halfar_40km

      - name: Download temporary scoreboard file for integrated_tests/idealised/Halfar_dome/Halfar_40km
        uses: actions/download-artifact@v4
        with:
          name: temporary_scoreboard_integrated_tests_idealised_Halfar_dome_Halfar_40km
          path: automated_testing/integrated_tests/idealised/Halfar_dome/Halfar_40km

# integrated_tests/idealised/Halfar_dome/Halfar_5km

      - name: Download temporary scoreboard file for integrated_tests/idealised/Halfar_dome/Halfar_5km
        uses: actions/download-artifact@v4
        with:
          name: temporary_scoreboard_integrated_tests_idealised_Halfar_dome_Halfar_5km
          path: automated_testing/integrated_tests/idealised/Halfar_dome/Halfar_5km
