name: UFEMISM Test Suite - run integrated tests
run-name: ${{ github.actor }} - UFEMISM Test Suite - run integrated tests
on:
  workflow_call:

jobs:

  integrated_tests_idealised_Halfar_dome_Halfar_10km:
    uses: ./.github/workflows/zz_integrated_tests_idealised_Halfar_dome_Halfar_10km.yml

  integrated_tests_idealised_Halfar_dome_Halfar_20km:
    uses: ./.github/workflows/zz_integrated_tests_idealised_Halfar_dome_Halfar_20km.yml

  integrated_tests_idealised_Halfar_dome_Halfar_40km:
    uses: ./.github/workflows/zz_integrated_tests_idealised_Halfar_dome_Halfar_40km.yml

  integrated_tests_idealised_Halfar_dome_Halfar_5km:
    uses: ./.github/workflows/zz_integrated_tests_idealised_Halfar_dome_Halfar_5km.yml
